--------------------------------------------------------------------------------------------------
-- 062_fs_final.sql
--
-- ماژول «صورت‌های مالی»، تکمیل نهایی (۲۰۲۶-۱۰-۰۴): قطعه‌های ط-۲ به بعد — docs/fs-module.md §۱۴. پس از 061.
--
-- ⚠️⚠️ DO NOT RUN THIS AGAINST ANY DATABASE WITHOUT EXPLICIT PROJECT-OWNER APPROVAL. ⚠️⚠️
--------------------------------------------------------------------------------------------------

-- ط-۲: دسترسی سه‌بُعدی. OPERATIONS = بیت‌های FsOperation: 1=مشاهده،2=تهیه،4=تغییر قالب،8=فعال‌سازی قالب،
-- 16=تأیید،32=انتشار،64=بستن دوره،128=مدیریت دسترسی. جدول خالی = همه مجاز (رفتار قبلی).
CREATE TABLE TB_FS_PERMISSION
(
    ID           CHAR(36)      NOT NULL,
    USERID       VARCHAR2(10)  NOT NULL,
    USERNAME     VARCHAR2(200),
    VAHEDCODE    VARCHAR2(4)   NOT NULL,
    INCLUDE_SUB  NUMBER(1)     DEFAULT 1 NOT NULL,
    OPERATIONS   NUMBER(5)     NOT NULL,
    CREATEDDATE  TIMESTAMP     NOT NULL,
    UPDATEDDATE  TIMESTAMP,
    ADDUSERID    VARCHAR2(10)  NOT NULL,
    CHANGEUSERID VARCHAR2(10),
    ISDELETED    NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_FS_PERMISSION PRIMARY KEY (ID)
);
CREATE INDEX IDX_FS_PERMISSION_USER ON TB_FS_PERMISSION (USERID);

--------------------------------------------------------------------------------------------------
-- ط-۳ تا ط-۸: تنظیمات مجموعه، درخت واحد و کاربرگ هر اجرا، حذف فی‌مابین، شرکت‌های تابعه (تراز، نرخ تسعیر)، XBRL.
-- TB_FS_RUN_UNIT.KIND: 1=واحد، 2=شرکت تابعه. TB_FS_RUN_ELIM.STATUS: 1=تطبیق،2=در آستانه،3=عدم تطبیق،4=طرف مقابل ندارد.
-- TB_FS_ENTITY_TB.ACC_CLASS: 1=دارایی/بدهی، 2=حقوق مالکانه، 3=سود و زیان. TB_FS_XBRL_MAP.PERIOD_TYPE: 1=instant، 2=duration.
--------------------------------------------------------------------------------------------------
CREATE TABLE TB_FS_SETTING
(
    ID               CHAR(36) NOT NULL,
    VAHEDCODE        VARCHAR2(4),
    FRAMEWORK        NUMBER(2) NOT NULL,
    SETTING_KEY      VARCHAR2(50) NOT NULL,
    SETTING_VALUE    VARCHAR2(2000),
    CREATEDDATE      TIMESTAMP NOT NULL,
    UPDATEDDATE      TIMESTAMP,
    ADDUSERID        VARCHAR2(10) NOT NULL,
    CHANGEUSERID     VARCHAR2(10),
    CONSTRAINT PK_FS_SETTING PRIMARY KEY (ID)
);

CREATE TABLE TB_FS_RUN_UNIT
(
    ID               CHAR(36) NOT NULL,
    RUN_ID           CHAR(36) NOT NULL,
    VAHEDCODE        VARCHAR2(4) NOT NULL,
    UNIT_CODE        VARCHAR2(10) NOT NULL,
    UNIT_NAME        VARCHAR2(200),
    PARENT_CODE      VARCHAR2(10),
    GROUP_CODE       VARCHAR2(10) NOT NULL,
    KIND             NUMBER(1) NOT NULL,
    CONSTRAINT PK_FS_RUN_UNIT PRIMARY KEY (ID),
    CONSTRAINT FK_FS_RUN_UNIT_RUN FOREIGN KEY (RUN_ID) REFERENCES TB_FS_RUN (ID)
);
CREATE INDEX IDX_FS_RUN_UNIT_RUN ON TB_FS_RUN_UNIT (RUN_ID, VAHEDCODE);

CREATE TABLE TB_FS_RUN_ROW_GROUP
(
    ID               CHAR(36) NOT NULL,
    RUN_ID           CHAR(36) NOT NULL,
    VAHEDCODE        VARCHAR2(4) NOT NULL,
    RUN_ROW_ID       CHAR(36) NOT NULL,
    GROUP_CODE       VARCHAR2(10) NOT NULL,
    AMOUNT_CUR       NUMBER(28),
    AMOUNT_PRV       NUMBER(28),
    CONSTRAINT PK_FS_RUN_ROW_GROUP PRIMARY KEY (ID),
    CONSTRAINT FK_FS_RUN_ROW_GROUP_RUN FOREIGN KEY (RUN_ID) REFERENCES TB_FS_RUN (ID)
);
CREATE INDEX IDX_FS_RUN_ROW_GROUP_RUN ON TB_FS_RUN_ROW_GROUP (RUN_ID, VAHEDCODE);

CREATE TABLE TB_FS_ELIM_RULE
(
    ID               CHAR(36) NOT NULL,
    VAHEDCODE        VARCHAR2(4),
    FRAMEWORK        NUMBER(2) NOT NULL,
    CODE             VARCHAR2(20) NOT NULL,
    TITLE_FA         VARCHAR2(500) NOT NULL,
    LEFT_SELECTOR    VARCHAR2(1000) NOT NULL,
    RIGHT_SELECTOR   VARCHAR2(1000) NOT NULL,
    TOLERANCE        NUMBER(28) NOT NULL,
    IS_ACTIVE        NUMBER(1) DEFAULT 1 NOT NULL,
    CREATEDDATE      TIMESTAMP NOT NULL,
    UPDATEDDATE      TIMESTAMP,
    ADDUSERID        VARCHAR2(10) NOT NULL,
    CHANGEUSERID     VARCHAR2(10),
    ISDELETED        NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_FS_ELIM_RULE PRIMARY KEY (ID)
);

CREATE TABLE TB_FS_RUN_ELIM
(
    ID               CHAR(36) NOT NULL,
    RUN_ID           CHAR(36) NOT NULL,
    VAHEDCODE        VARCHAR2(4) NOT NULL,
    RULE_CODE        VARCHAR2(20) NOT NULL,
    TITLE_FA         VARCHAR2(500) NOT NULL,
    LEFT_AMOUNT      NUMBER(28) NOT NULL,
    RIGHT_AMOUNT     NUMBER(28) NOT NULL,
    DIFFERENCE       NUMBER(28) NOT NULL,
    STATUS           NUMBER(1) NOT NULL,
    CONSTRAINT PK_FS_RUN_ELIM PRIMARY KEY (ID),
    CONSTRAINT FK_FS_RUN_ELIM_RUN FOREIGN KEY (RUN_ID) REFERENCES TB_FS_RUN (ID)
);
CREATE INDEX IDX_FS_RUN_ELIM_RUN ON TB_FS_RUN_ELIM (RUN_ID, VAHEDCODE);

CREATE TABLE TB_FS_ENTITY
(
    ID               CHAR(36) NOT NULL,
    VAHEDCODE        VARCHAR2(4) NOT NULL,
    CODE             VARCHAR2(4) NOT NULL,
    TITLE_FA         VARCHAR2(500) NOT NULL,
    CURRENCY         VARCHAR2(3) NOT NULL,
    OWNERSHIP        NUMBER(7,4) NOT NULL,
    IS_ACTIVE        NUMBER(1) DEFAULT 1 NOT NULL,
    CREATEDDATE      TIMESTAMP NOT NULL,
    UPDATEDDATE      TIMESTAMP,
    ADDUSERID        VARCHAR2(10) NOT NULL,
    CHANGEUSERID     VARCHAR2(10),
    ISDELETED        NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_FS_ENTITY PRIMARY KEY (ID)
);

CREATE TABLE TB_FS_ENTITY_TB
(
    ID               CHAR(36) NOT NULL,
    ENTITY_ID        CHAR(36) NOT NULL,
    YEAR             CHAR(4) NOT NULL,
    TO_MONTH         NUMBER(2) NOT NULL,
    ACCCODE          VARCHAR2(20) NOT NULL,
    SOURCE_ACCCODE   VARCHAR2(50),
    SOURCE_ACCNAME   VARCHAR2(500),
    ACC_CLASS        NUMBER(1) NOT NULL,
    OPENING_DEBTOR   NUMBER(28,2) NOT NULL,
    OPENING_CREDITOR NUMBER(28,2) NOT NULL,
    PERIOD_DEBTOR    NUMBER(28,2) NOT NULL,
    PERIOD_CREDITOR  NUMBER(28,2) NOT NULL,
    CREATEDDATE      TIMESTAMP NOT NULL,
    ADDUSERID        VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_FS_ENTITY_TB PRIMARY KEY (ID),
    CONSTRAINT FK_FS_ENTITY_TB_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES TB_FS_ENTITY (ID)
);
CREATE INDEX IDX_FS_ENTITY_TB_PERIOD ON TB_FS_ENTITY_TB (ENTITY_ID, YEAR);

CREATE TABLE TB_FS_ENTITY_RATE
(
    ID               CHAR(36) NOT NULL,
    ENTITY_ID        CHAR(36) NOT NULL,
    YEAR             CHAR(4) NOT NULL,
    TO_MONTH         NUMBER(2) NOT NULL,
    OPENING_RATE     NUMBER(18,6) NOT NULL,
    CLOSING_RATE     NUMBER(18,6) NOT NULL,
    AVERAGE_RATE     NUMBER(18,6) NOT NULL,
    CREATEDDATE      TIMESTAMP NOT NULL,
    ADDUSERID        VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_FS_ENTITY_RATE PRIMARY KEY (ID),
    CONSTRAINT FK_FS_ENTITY_RATE_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES TB_FS_ENTITY (ID)
);
CREATE INDEX IDX_FS_ENTITY_RATE_PERIOD ON TB_FS_ENTITY_RATE (ENTITY_ID, YEAR);

CREATE TABLE TB_FS_XBRL_MAP
(
    ID               CHAR(36) NOT NULL,
    VAHEDCODE        VARCHAR2(4),
    TEMPLATE_CODE    VARCHAR2(50) NOT NULL,
    ROW_CODE         VARCHAR2(20) NOT NULL,
    ELEMENT          VARCHAR2(200) NOT NULL,
    PERIOD_TYPE      NUMBER(1) NOT NULL,
    CREATEDDATE      TIMESTAMP NOT NULL,
    ADDUSERID        VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_FS_XBRL_MAP PRIMARY KEY (ID)
);

-- اجرا: تلفیق با شرکت‌های تابعه.
ALTER TABLE TB_FS_RUN ADD (
    INCLUDE_ENTITIES NUMBER(1) DEFAULT 0 NOT NULL
);
