--------------------------------------------------------------------------------------------------
-- 067_operation_templates.sql
--
-- Agent-UX فاز ۱ (۲۰۲۶-۱۰-۰۶): الگوی عملیات و ردپای اجرا. کاربر غیرمالی به‌جای کل/معین/تفصیلی یک
-- «عملیات» انتخاب می‌کند و سند موقت را موتور قطعی از روی الگوی ستاد می‌سازد.
-- نگاشت: backend/src/Accounting.Infrastructure/OperationTemplates/OperationTemplateMappings.cs
-- بدون این اسکریپت فقط endpointهای /api/operations خطا می‌دهند؛ بقیهٔ سامانه اثری نمی‌گیرد.
--
-- ⚠️⚠️ DO NOT RUN THIS AGAINST ANY DATABASE WITHOUT EXPLICIT PROJECT-OWNER APPROVAL. ⚠️⚠️
--------------------------------------------------------------------------------------------------

CREATE TABLE TB_OP_TEMPLATE
(
    ID                    CHAR(36)        NOT NULL,
    CODE                  VARCHAR2(50)    NOT NULL,
    TITLE                 VARCHAR2(200)   NOT NULL,
    DESCRIPTION           VARCHAR2(2000)  NOT NULL,
    VOUCHER_DESC_PATTERN  VARCHAR2(500)   NOT NULL,
    ISACTIVE              NUMBER(1)       DEFAULT 1 NOT NULL,
    ADDUSERID             VARCHAR2(10)    NOT NULL,
    CREATEDDATE           TIMESTAMP       NOT NULL,
    CONSTRAINT PK_OP_TEMPLATE PRIMARY KEY (ID),
    CONSTRAINT UK_OP_TEMPLATE_CODE UNIQUE (CODE)
);

CREATE TABLE TB_OP_TEMPLATE_PARAM
(
    ID              CHAR(36)       NOT NULL,
    TEMPLATE_ID     CHAR(36)       NOT NULL,
    PARAM_KEY       VARCHAR2(40)   NOT NULL,
    TITLE           VARCHAR2(200)  NOT NULL,
    PARAM_TYPE      NUMBER(1)      NOT NULL,   -- 1 مبلغ، 2 تفصیلی، 3 متن، 4 تاریخ
    TAFSILGROUP_ID  CHAR(36),
    ISREQUIRED      NUMBER(1)      DEFAULT 1 NOT NULL,
    ASK_PROMPT      VARCHAR2(500)  NOT NULL,
    SORT_ORDER      NUMBER(5)      NOT NULL,
    CONSTRAINT PK_OP_TEMPLATE_PARAM PRIMARY KEY (ID),
    CONSTRAINT UK_OP_PARAM_KEY UNIQUE (TEMPLATE_ID, PARAM_KEY),
    CONSTRAINT FK_OP_PARAM_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES TB_OP_TEMPLATE (ID) ON DELETE CASCADE,
    CONSTRAINT FK_OP_PARAM_TAFSILGROUP FOREIGN KEY (TAFSILGROUP_ID) REFERENCES TB_TAFSIL_GROUP (ID),
    CONSTRAINT CK_OP_PARAM_TYPE CHECK (PARAM_TYPE IN (1, 2, 3, 4)),
    CONSTRAINT CK_OP_PARAM_GROUP CHECK ((PARAM_TYPE = 2 AND TAFSILGROUP_ID IS NOT NULL)
                                     OR (PARAM_TYPE <> 2 AND TAFSILGROUP_ID IS NULL))
);

CREATE TABLE TB_OP_TEMPLATE_LINE
(
    ID                CHAR(36)       NOT NULL,
    TEMPLATE_ID       CHAR(36)       NOT NULL,
    SIDE              NUMBER(1)      NOT NULL,   -- 1 بدهکار، 2 بستانکار
    ACCOUNT_ID        CHAR(36)       NOT NULL,   -- معین (TB_ACCOUNTCODE)
    AMOUNT_PARAM_KEY  VARCHAR2(40),
    PERCENT_VALUE     NUMBER(9,4)    DEFAULT 100 NOT NULL,
    ISBALANCING       NUMBER(1)      DEFAULT 0 NOT NULL,
    DESC_PATTERN      VARCHAR2(500),
    SORT_ORDER        NUMBER(5)      NOT NULL,
    CONSTRAINT PK_OP_TEMPLATE_LINE PRIMARY KEY (ID),
    CONSTRAINT FK_OP_LINE_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES TB_OP_TEMPLATE (ID) ON DELETE CASCADE,
    CONSTRAINT FK_OP_LINE_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES TB_ACCOUNTCODE (ID),
    CONSTRAINT CK_OP_LINE_SIDE CHECK (SIDE IN (1, 2))
);

CREATE INDEX IX_OP_LINE_TEMPLATE ON TB_OP_TEMPLATE_LINE (TEMPLATE_ID);

CREATE TABLE TB_OP_TEMPLATE_LINE_DETAIL
(
    ID                CHAR(36)      NOT NULL,
    LINE_ID           CHAR(36)      NOT NULL,
    LEVEL_NO          NUMBER(1)     NOT NULL,   -- همان TB_LEVEL_TAFSIL.LEVEL_CODE (۱..۷)
    PARAM_KEY         VARCHAR2(40),
    FIXED_TAFSILI_ID  CHAR(36),
    CONSTRAINT PK_OP_TEMPLATE_LINE_DETAIL PRIMARY KEY (ID),
    CONSTRAINT UK_OP_LINEDET_LEVEL UNIQUE (LINE_ID, LEVEL_NO),
    CONSTRAINT FK_OP_LINEDET_LINE FOREIGN KEY (LINE_ID) REFERENCES TB_OP_TEMPLATE_LINE (ID) ON DELETE CASCADE,
    CONSTRAINT FK_OP_LINEDET_TAFSILI FOREIGN KEY (FIXED_TAFSILI_ID) REFERENCES TB_TAFSILI (ID),
    CONSTRAINT CK_OP_LINEDET_ONE_SOURCE CHECK ((PARAM_KEY IS NULL AND FIXED_TAFSILI_ID IS NOT NULL)
                                            OR (PARAM_KEY IS NOT NULL AND FIXED_TAFSILI_ID IS NULL))
);

CREATE TABLE TB_OP_EXECUTION
(
    ID                 CHAR(36)        NOT NULL,
    CLIENT_REQUEST_ID  CHAR(36)        NOT NULL,
    TEMPLATE_ID        CHAR(36),                    -- null = سند آزاد (MANUAL)
    TEMPLATE_CODE      VARCHAR2(50)    NOT NULL,
    VAHEDCODE          VARCHAR2(4)     NOT NULL,
    INPUT_JSON         VARCHAR2(4000)  NOT NULL,
    VOUCHER_ID         CHAR(36)        NOT NULL,
    VOUCHER_NO         VARCHAR2(50)    NOT NULL,
    CHANNEL            VARCHAR2(20)    NOT NULL,   -- Form | Compose | Agent
    ADDUSERID          VARCHAR2(10)    NOT NULL,
    CREATEDDATE        TIMESTAMP       NOT NULL,
    CONSTRAINT PK_OP_EXECUTION PRIMARY KEY (ID),
    CONSTRAINT UK_OP_EXEC_CLIENT_REQ UNIQUE (CLIENT_REQUEST_ID),   -- Idempotency
    CONSTRAINT FK_OP_EXEC_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES TB_OP_TEMPLATE (ID),
    CONSTRAINT FK_OP_EXEC_VOUCHER FOREIGN KEY (VOUCHER_ID) REFERENCES TB_VOUCHERSHEAD (ID)
);

CREATE INDEX IX_OP_EXEC_VAHED ON TB_OP_EXECUTION (VAHEDCODE, CREATEDDATE);
CREATE INDEX IX_OP_EXEC_VOUCHER ON TB_OP_EXECUTION (VOUCHER_ID);
