//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elmDrmd
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/Sorat/CentralAccount", ConfigurationName="elmDrmd.CentralAccountSoap")]
    public interface CentralAccountSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/SendSorat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SendSoratAsync(
                    string vSORAT_DATE, 
                    string vSORAT_ORDPAY, 
                    string vSORAT_RCVTYPE, 
                    string vSORAT_RCVNO, 
                    string vSORAT_ATTRIB, 
                    string vSORAT_MDATE, 
                    string vSORAT_RETU, 
                    string vSORAT_PASS, 
                    string vSORAT_COMMENT, 
                    string vCREATEUID, 
                    string vCREATEDT, 
                    string vSORAT_RADIF, 
                    double vSORAT_MANDEH, 
                    string vEDITUID, 
                    string vEDITDT, 
                    string vSORAT_BANK, 
                    double vSORAT_PRICE1, 
                    double vSORAT_PRICE2, 
                    string vSORAT_DESC, 
                    int vSORAT_ROWH, 
                    string vSORAT_STAT, 
                    string vSORAT_EFDATE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/GetDrmd_Card", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetDrmd_CardAsync(string brchcode, string ordpay, string rcvno, string price, string crd_date, string rcvtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/GetDrmd_Sorat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetDrmd_SoratAsync(string brchcode, string ordpay, string rcvno, string price, string crd_date, string rcvtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/GetRadif_Bank", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetRadif_BankAsync(string brchcode, string bnkcode, string bnkhesab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/SetLetter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SetLetterAsync(elmDrmd.clsletter oclsletter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/Insert_Letter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Insert_LetterAsync(elmDrmd.clsletter oclsletter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/Send_Ok", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Send_OkAsync(string brchcode, string serial, string ordpay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/Send_Letter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Send_LetterAsync(elmDrmd.clsletter oclsletter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/GetDrmd_Amar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetDrmd_AmarAsync(string brchcode, string sdate, string edate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/GetDrmd_AmarKol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetDrmd_AmarKolAsync(string brchcode, string sdate, string edate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/Send_Letter_New", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Send_Letter_NewAsync(elmDrmd.clsletter oclsletter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/Send_Letter_Log", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Send_Letter_LogAsync(elmDrmd.clsletter oclsletter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/Send_LetterN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Send_LetterNAsync(elmDrmd.clsLetterN oclsLetterN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/Send_Letter_Tahator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Send_Letter_TahatorAsync(elmDrmd.clsLetterTahator oclsLetterTahator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/GetMafasaInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetMafasaInfoAsync(string brchCode, string mafasaNo, string rcntNo, string rcntDat, string rcontractfee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/Send_LetterGno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Send_LetterGnoAsync(elmDrmd.clsletter oclsletter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorat/CentralAccount/Send_Letter_NewGno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Send_Letter_NewGnoAsync(elmDrmd.clsletter oclsletter);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Sorat/CentralAccount")]
    public partial class clsletter
    {
        
        private string lETTER_SERIALField;
        
        private string bRHCODEField;
        
        private string lETTER_NOField;
        
        private string lETTER_DATEField;
        
        private string lETTER_NAMField;
        
        private string lETTER_LNOField;
        
        private string lETTER_LDATEField;
        
        private string lETTER_TYPEField;
        
        private string lETTER_PRICE1Field;
        
        private string lETTER_CODE1Field;
        
        private string lETTER_PRICE2Field;
        
        private string lETTER_CODE2Field;
        
        private string lETTER_OBJDATEField;
        
        private string lETTER_RABETField;
        
        private string lETTER_SANADFLAGField;
        
        private string cREATEUIDField;
        
        private string cREATEDTField;
        
        private string lETTER_PRINTField;
        
        private string lETTER_FLAGField;
        
        private string lETTER_SODORField;
        
        private string lETTER_DELField;
        
        private string saveBRHCODEField;
        
        private string bES_CNTDATEField;
        
        private string bES_CNTNOField;
        
        private string bES_EMPZFLAGField;
        
        private string bES_FUNCTIONDATEField;
        
        private string rWSHIDField;
        
        private string rWSHNAMEField;
        
        private string iDNOField;
        
        private string cODEDIGITField;
        
        private string oURAG_GNOField;
        
        private string oURAG_SDATEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LETTER_SERIAL
        {
            get
            {
                return this.lETTER_SERIALField;
            }
            set
            {
                this.lETTER_SERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BRHCODE
        {
            get
            {
                return this.bRHCODEField;
            }
            set
            {
                this.bRHCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LETTER_NO
        {
            get
            {
                return this.lETTER_NOField;
            }
            set
            {
                this.lETTER_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LETTER_DATE
        {
            get
            {
                return this.lETTER_DATEField;
            }
            set
            {
                this.lETTER_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LETTER_NAM
        {
            get
            {
                return this.lETTER_NAMField;
            }
            set
            {
                this.lETTER_NAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LETTER_LNO
        {
            get
            {
                return this.lETTER_LNOField;
            }
            set
            {
                this.lETTER_LNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LETTER_LDATE
        {
            get
            {
                return this.lETTER_LDATEField;
            }
            set
            {
                this.lETTER_LDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LETTER_TYPE
        {
            get
            {
                return this.lETTER_TYPEField;
            }
            set
            {
                this.lETTER_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LETTER_PRICE1
        {
            get
            {
                return this.lETTER_PRICE1Field;
            }
            set
            {
                this.lETTER_PRICE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LETTER_CODE1
        {
            get
            {
                return this.lETTER_CODE1Field;
            }
            set
            {
                this.lETTER_CODE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string LETTER_PRICE2
        {
            get
            {
                return this.lETTER_PRICE2Field;
            }
            set
            {
                this.lETTER_PRICE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string LETTER_CODE2
        {
            get
            {
                return this.lETTER_CODE2Field;
            }
            set
            {
                this.lETTER_CODE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string LETTER_OBJDATE
        {
            get
            {
                return this.lETTER_OBJDATEField;
            }
            set
            {
                this.lETTER_OBJDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string LETTER_RABET
        {
            get
            {
                return this.lETTER_RABETField;
            }
            set
            {
                this.lETTER_RABETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string LETTER_SANADFLAG
        {
            get
            {
                return this.lETTER_SANADFLAGField;
            }
            set
            {
                this.lETTER_SANADFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CREATEUID
        {
            get
            {
                return this.cREATEUIDField;
            }
            set
            {
                this.cREATEUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CREATEDT
        {
            get
            {
                return this.cREATEDTField;
            }
            set
            {
                this.cREATEDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string LETTER_PRINT
        {
            get
            {
                return this.lETTER_PRINTField;
            }
            set
            {
                this.lETTER_PRINTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string LETTER_FLAG
        {
            get
            {
                return this.lETTER_FLAGField;
            }
            set
            {
                this.lETTER_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string LETTER_SODOR
        {
            get
            {
                return this.lETTER_SODORField;
            }
            set
            {
                this.lETTER_SODORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string LETTER_DEL
        {
            get
            {
                return this.lETTER_DELField;
            }
            set
            {
                this.lETTER_DELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string saveBRHCODE
        {
            get
            {
                return this.saveBRHCODEField;
            }
            set
            {
                this.saveBRHCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string BES_CNTDATE
        {
            get
            {
                return this.bES_CNTDATEField;
            }
            set
            {
                this.bES_CNTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string BES_CNTNO
        {
            get
            {
                return this.bES_CNTNOField;
            }
            set
            {
                this.bES_CNTNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string BES_EMPZFLAG
        {
            get
            {
                return this.bES_EMPZFLAGField;
            }
            set
            {
                this.bES_EMPZFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string BES_FUNCTIONDATE
        {
            get
            {
                return this.bES_FUNCTIONDATEField;
            }
            set
            {
                this.bES_FUNCTIONDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string RWSHID
        {
            get
            {
                return this.rWSHIDField;
            }
            set
            {
                this.rWSHIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string RWSHNAME
        {
            get
            {
                return this.rWSHNAMEField;
            }
            set
            {
                this.rWSHNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string IDNO
        {
            get
            {
                return this.iDNOField;
            }
            set
            {
                this.iDNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string CODEDIGIT
        {
            get
            {
                return this.cODEDIGITField;
            }
            set
            {
                this.cODEDIGITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string OURAG_GNO
        {
            get
            {
                return this.oURAG_GNOField;
            }
            set
            {
                this.oURAG_GNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string OURAG_SDATE
        {
            get
            {
                return this.oURAG_SDATEField;
            }
            set
            {
                this.oURAG_SDATEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Sorat/CentralAccount")]
    public partial class clsLetterTahator
    {
        
        private string lETTER_SERIALField;
        
        private string bRHCODEField;
        
        private string lETTER_NOField;
        
        private string lETTER_DATEField;
        
        private string lETTER_NAMField;
        
        private string lETTER_LNOField;
        
        private string lETTER_LDATEField;
        
        private string lETTER_TYPEField;
        
        private string lETTER_PRICE1Field;
        
        private string lETTER_CODE1Field;
        
        private string lETTER_PRICE2Field;
        
        private string lETTER_CODE2Field;
        
        private string lETTER_OBJDATEField;
        
        private string lETTER_RABETField;
        
        private string lETTER_SANADFLAGField;
        
        private string cREATEUIDField;
        
        private string cREATEDTField;
        
        private string lETTER_PRINTField;
        
        private string lETTER_FLAGField;
        
        private string lETTER_SODORField;
        
        private string lETTER_DELField;
        
        private string saveBRHCODEField;
        
        private string bES_CNTDATEField;
        
        private string bES_CNTNOField;
        
        private string bES_EMPZFLAGField;
        
        private string bES_FUNCTIONDATEField;
        
        private string rWSHIDField;
        
        private string rWSHNAMEField;
        
        private string iDNOField;
        
        private string cODEDIGITField;
        
        private string cWS_DBTNOField;
        
        private string kEYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LETTER_SERIAL
        {
            get
            {
                return this.lETTER_SERIALField;
            }
            set
            {
                this.lETTER_SERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BRHCODE
        {
            get
            {
                return this.bRHCODEField;
            }
            set
            {
                this.bRHCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LETTER_NO
        {
            get
            {
                return this.lETTER_NOField;
            }
            set
            {
                this.lETTER_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LETTER_DATE
        {
            get
            {
                return this.lETTER_DATEField;
            }
            set
            {
                this.lETTER_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LETTER_NAM
        {
            get
            {
                return this.lETTER_NAMField;
            }
            set
            {
                this.lETTER_NAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LETTER_LNO
        {
            get
            {
                return this.lETTER_LNOField;
            }
            set
            {
                this.lETTER_LNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LETTER_LDATE
        {
            get
            {
                return this.lETTER_LDATEField;
            }
            set
            {
                this.lETTER_LDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LETTER_TYPE
        {
            get
            {
                return this.lETTER_TYPEField;
            }
            set
            {
                this.lETTER_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LETTER_PRICE1
        {
            get
            {
                return this.lETTER_PRICE1Field;
            }
            set
            {
                this.lETTER_PRICE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LETTER_CODE1
        {
            get
            {
                return this.lETTER_CODE1Field;
            }
            set
            {
                this.lETTER_CODE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string LETTER_PRICE2
        {
            get
            {
                return this.lETTER_PRICE2Field;
            }
            set
            {
                this.lETTER_PRICE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string LETTER_CODE2
        {
            get
            {
                return this.lETTER_CODE2Field;
            }
            set
            {
                this.lETTER_CODE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string LETTER_OBJDATE
        {
            get
            {
                return this.lETTER_OBJDATEField;
            }
            set
            {
                this.lETTER_OBJDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string LETTER_RABET
        {
            get
            {
                return this.lETTER_RABETField;
            }
            set
            {
                this.lETTER_RABETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string LETTER_SANADFLAG
        {
            get
            {
                return this.lETTER_SANADFLAGField;
            }
            set
            {
                this.lETTER_SANADFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CREATEUID
        {
            get
            {
                return this.cREATEUIDField;
            }
            set
            {
                this.cREATEUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CREATEDT
        {
            get
            {
                return this.cREATEDTField;
            }
            set
            {
                this.cREATEDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string LETTER_PRINT
        {
            get
            {
                return this.lETTER_PRINTField;
            }
            set
            {
                this.lETTER_PRINTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string LETTER_FLAG
        {
            get
            {
                return this.lETTER_FLAGField;
            }
            set
            {
                this.lETTER_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string LETTER_SODOR
        {
            get
            {
                return this.lETTER_SODORField;
            }
            set
            {
                this.lETTER_SODORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string LETTER_DEL
        {
            get
            {
                return this.lETTER_DELField;
            }
            set
            {
                this.lETTER_DELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string saveBRHCODE
        {
            get
            {
                return this.saveBRHCODEField;
            }
            set
            {
                this.saveBRHCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string BES_CNTDATE
        {
            get
            {
                return this.bES_CNTDATEField;
            }
            set
            {
                this.bES_CNTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string BES_CNTNO
        {
            get
            {
                return this.bES_CNTNOField;
            }
            set
            {
                this.bES_CNTNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string BES_EMPZFLAG
        {
            get
            {
                return this.bES_EMPZFLAGField;
            }
            set
            {
                this.bES_EMPZFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string BES_FUNCTIONDATE
        {
            get
            {
                return this.bES_FUNCTIONDATEField;
            }
            set
            {
                this.bES_FUNCTIONDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string RWSHID
        {
            get
            {
                return this.rWSHIDField;
            }
            set
            {
                this.rWSHIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string RWSHNAME
        {
            get
            {
                return this.rWSHNAMEField;
            }
            set
            {
                this.rWSHNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string IDNO
        {
            get
            {
                return this.iDNOField;
            }
            set
            {
                this.iDNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string CODEDIGIT
        {
            get
            {
                return this.cODEDIGITField;
            }
            set
            {
                this.cODEDIGITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string CWS_DBTNO
        {
            get
            {
                return this.cWS_DBTNOField;
            }
            set
            {
                this.cWS_DBTNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string KEY
        {
            get
            {
                return this.kEYField;
            }
            set
            {
                this.kEYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Sorat/CentralAccount")]
    public partial class clsLetterN
    {
        
        private string lETTER_SERIALField;
        
        private string bRHCODEField;
        
        private string lETTER_NOField;
        
        private string lETTER_DATEField;
        
        private string lETTER_NAMField;
        
        private string lETTER_LNOField;
        
        private string lETTER_LDATEField;
        
        private string lETTER_TYPEField;
        
        private string lETTER_PRICE1Field;
        
        private string lETTER_CODE1Field;
        
        private string lETTER_PRICE2Field;
        
        private string lETTER_CODE2Field;
        
        private string lETTER_OBJDATEField;
        
        private string lETTER_RABETField;
        
        private string lETTER_SANADFLAGField;
        
        private string cREATEUIDField;
        
        private string cREATEDTField;
        
        private string lETTER_PRINTField;
        
        private string lETTER_FLAGField;
        
        private string lETTER_SODORField;
        
        private string lETTER_DELField;
        
        private string saveBRHCODEField;
        
        private string bES_CNTDATEField;
        
        private string bES_CNTNOField;
        
        private string bES_EMPZFLAGField;
        
        private string bES_FUNCTIONDATEField;
        
        private string rWSHIDField;
        
        private string rWSHNAMEField;
        
        private string iDNOField;
        
        private string cODEDIGITField;
        
        private string cWS_DBTNOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LETTER_SERIAL
        {
            get
            {
                return this.lETTER_SERIALField;
            }
            set
            {
                this.lETTER_SERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BRHCODE
        {
            get
            {
                return this.bRHCODEField;
            }
            set
            {
                this.bRHCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LETTER_NO
        {
            get
            {
                return this.lETTER_NOField;
            }
            set
            {
                this.lETTER_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LETTER_DATE
        {
            get
            {
                return this.lETTER_DATEField;
            }
            set
            {
                this.lETTER_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LETTER_NAM
        {
            get
            {
                return this.lETTER_NAMField;
            }
            set
            {
                this.lETTER_NAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LETTER_LNO
        {
            get
            {
                return this.lETTER_LNOField;
            }
            set
            {
                this.lETTER_LNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LETTER_LDATE
        {
            get
            {
                return this.lETTER_LDATEField;
            }
            set
            {
                this.lETTER_LDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LETTER_TYPE
        {
            get
            {
                return this.lETTER_TYPEField;
            }
            set
            {
                this.lETTER_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LETTER_PRICE1
        {
            get
            {
                return this.lETTER_PRICE1Field;
            }
            set
            {
                this.lETTER_PRICE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LETTER_CODE1
        {
            get
            {
                return this.lETTER_CODE1Field;
            }
            set
            {
                this.lETTER_CODE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string LETTER_PRICE2
        {
            get
            {
                return this.lETTER_PRICE2Field;
            }
            set
            {
                this.lETTER_PRICE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string LETTER_CODE2
        {
            get
            {
                return this.lETTER_CODE2Field;
            }
            set
            {
                this.lETTER_CODE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string LETTER_OBJDATE
        {
            get
            {
                return this.lETTER_OBJDATEField;
            }
            set
            {
                this.lETTER_OBJDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string LETTER_RABET
        {
            get
            {
                return this.lETTER_RABETField;
            }
            set
            {
                this.lETTER_RABETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string LETTER_SANADFLAG
        {
            get
            {
                return this.lETTER_SANADFLAGField;
            }
            set
            {
                this.lETTER_SANADFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CREATEUID
        {
            get
            {
                return this.cREATEUIDField;
            }
            set
            {
                this.cREATEUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CREATEDT
        {
            get
            {
                return this.cREATEDTField;
            }
            set
            {
                this.cREATEDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string LETTER_PRINT
        {
            get
            {
                return this.lETTER_PRINTField;
            }
            set
            {
                this.lETTER_PRINTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string LETTER_FLAG
        {
            get
            {
                return this.lETTER_FLAGField;
            }
            set
            {
                this.lETTER_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string LETTER_SODOR
        {
            get
            {
                return this.lETTER_SODORField;
            }
            set
            {
                this.lETTER_SODORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string LETTER_DEL
        {
            get
            {
                return this.lETTER_DELField;
            }
            set
            {
                this.lETTER_DELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string saveBRHCODE
        {
            get
            {
                return this.saveBRHCODEField;
            }
            set
            {
                this.saveBRHCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string BES_CNTDATE
        {
            get
            {
                return this.bES_CNTDATEField;
            }
            set
            {
                this.bES_CNTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string BES_CNTNO
        {
            get
            {
                return this.bES_CNTNOField;
            }
            set
            {
                this.bES_CNTNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string BES_EMPZFLAG
        {
            get
            {
                return this.bES_EMPZFLAGField;
            }
            set
            {
                this.bES_EMPZFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string BES_FUNCTIONDATE
        {
            get
            {
                return this.bES_FUNCTIONDATEField;
            }
            set
            {
                this.bES_FUNCTIONDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string RWSHID
        {
            get
            {
                return this.rWSHIDField;
            }
            set
            {
                this.rWSHIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string RWSHNAME
        {
            get
            {
                return this.rWSHNAMEField;
            }
            set
            {
                this.rWSHNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string IDNO
        {
            get
            {
                return this.iDNOField;
            }
            set
            {
                this.iDNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string CODEDIGIT
        {
            get
            {
                return this.cODEDIGITField;
            }
            set
            {
                this.cODEDIGITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string CWS_DBTNO
        {
            get
            {
                return this.cWS_DBTNOField;
            }
            set
            {
                this.cWS_DBTNOField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface CentralAccountSoapChannel : elmDrmd.CentralAccountSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CentralAccountSoapClient : System.ServiceModel.ClientBase<elmDrmd.CentralAccountSoap>, elmDrmd.CentralAccountSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CentralAccountSoapClient() : 
                base(CentralAccountSoapClient.GetDefaultBinding(), CentralAccountSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CentralAccountSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CentralAccountSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CentralAccountSoapClient.GetBindingForEndpoint(endpointConfiguration), CentralAccountSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CentralAccountSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CentralAccountSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CentralAccountSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CentralAccountSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CentralAccountSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> SendSoratAsync(
                    string vSORAT_DATE, 
                    string vSORAT_ORDPAY, 
                    string vSORAT_RCVTYPE, 
                    string vSORAT_RCVNO, 
                    string vSORAT_ATTRIB, 
                    string vSORAT_MDATE, 
                    string vSORAT_RETU, 
                    string vSORAT_PASS, 
                    string vSORAT_COMMENT, 
                    string vCREATEUID, 
                    string vCREATEDT, 
                    string vSORAT_RADIF, 
                    double vSORAT_MANDEH, 
                    string vEDITUID, 
                    string vEDITDT, 
                    string vSORAT_BANK, 
                    double vSORAT_PRICE1, 
                    double vSORAT_PRICE2, 
                    string vSORAT_DESC, 
                    int vSORAT_ROWH, 
                    string vSORAT_STAT, 
                    string vSORAT_EFDATE)
        {
            return base.Channel.SendSoratAsync(vSORAT_DATE, vSORAT_ORDPAY, vSORAT_RCVTYPE, vSORAT_RCVNO, vSORAT_ATTRIB, vSORAT_MDATE, vSORAT_RETU, vSORAT_PASS, vSORAT_COMMENT, vCREATEUID, vCREATEDT, vSORAT_RADIF, vSORAT_MANDEH, vEDITUID, vEDITDT, vSORAT_BANK, vSORAT_PRICE1, vSORAT_PRICE2, vSORAT_DESC, vSORAT_ROWH, vSORAT_STAT, vSORAT_EFDATE);
        }
        
        public System.Threading.Tasks.Task<string> GetDrmd_CardAsync(string brchcode, string ordpay, string rcvno, string price, string crd_date, string rcvtype)
        {
            return base.Channel.GetDrmd_CardAsync(brchcode, ordpay, rcvno, price, crd_date, rcvtype);
        }
        
        public System.Threading.Tasks.Task<string> GetDrmd_SoratAsync(string brchcode, string ordpay, string rcvno, string price, string crd_date, string rcvtype)
        {
            return base.Channel.GetDrmd_SoratAsync(brchcode, ordpay, rcvno, price, crd_date, rcvtype);
        }
        
        public System.Threading.Tasks.Task<string> GetRadif_BankAsync(string brchcode, string bnkcode, string bnkhesab)
        {
            return base.Channel.GetRadif_BankAsync(brchcode, bnkcode, bnkhesab);
        }
        
        public System.Threading.Tasks.Task<string> SetLetterAsync(elmDrmd.clsletter oclsletter)
        {
            return base.Channel.SetLetterAsync(oclsletter);
        }
        
        public System.Threading.Tasks.Task<string> Insert_LetterAsync(elmDrmd.clsletter oclsletter)
        {
            return base.Channel.Insert_LetterAsync(oclsletter);
        }
        
        public System.Threading.Tasks.Task<string> Send_OkAsync(string brchcode, string serial, string ordpay)
        {
            return base.Channel.Send_OkAsync(brchcode, serial, ordpay);
        }
        
        public System.Threading.Tasks.Task<string> Send_LetterAsync(elmDrmd.clsletter oclsletter)
        {
            return base.Channel.Send_LetterAsync(oclsletter);
        }
        
        public System.Threading.Tasks.Task<string> GetDrmd_AmarAsync(string brchcode, string sdate, string edate)
        {
            return base.Channel.GetDrmd_AmarAsync(brchcode, sdate, edate);
        }
        
        public System.Threading.Tasks.Task<string> GetDrmd_AmarKolAsync(string brchcode, string sdate, string edate)
        {
            return base.Channel.GetDrmd_AmarKolAsync(brchcode, sdate, edate);
        }
        
        public System.Threading.Tasks.Task<string> Send_Letter_NewAsync(elmDrmd.clsletter oclsletter)
        {
            return base.Channel.Send_Letter_NewAsync(oclsletter);
        }
        
        public System.Threading.Tasks.Task<string> Send_Letter_LogAsync(elmDrmd.clsletter oclsletter)
        {
            return base.Channel.Send_Letter_LogAsync(oclsletter);
        }
        
        public System.Threading.Tasks.Task<string> Send_LetterNAsync(elmDrmd.clsLetterN oclsLetterN)
        {
            return base.Channel.Send_LetterNAsync(oclsLetterN);
        }
        
        public System.Threading.Tasks.Task<string> Send_Letter_TahatorAsync(elmDrmd.clsLetterTahator oclsLetterTahator)
        {
            return base.Channel.Send_Letter_TahatorAsync(oclsLetterTahator);
        }
        
        public System.Threading.Tasks.Task<string> GetMafasaInfoAsync(string brchCode, string mafasaNo, string rcntNo, string rcntDat, string rcontractfee)
        {
            return base.Channel.GetMafasaInfoAsync(brchCode, mafasaNo, rcntNo, rcntDat, rcontractfee);
        }
        
        public System.Threading.Tasks.Task<string> Send_LetterGnoAsync(elmDrmd.clsletter oclsletter)
        {
            return base.Channel.Send_LetterGnoAsync(oclsletter);
        }
        
        public System.Threading.Tasks.Task<string> Send_Letter_NewGnoAsync(elmDrmd.clsletter oclsletter)
        {
            return base.Channel.Send_Letter_NewGnoAsync(oclsletter);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CentralAccountSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CentralAccountSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.1.18:4040/Sorat/CentralAccount.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CentralAccountSoapClient.GetBindingForEndpoint(EndpointConfiguration.CentralAccountSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CentralAccountSoapClient.GetEndpointAddress(EndpointConfiguration.CentralAccountSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            CentralAccountSoap,
        }
    }
}
